import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "../assets/css/style.css"
import "../assets/css/responsive.css"
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const dmSans = DM_Sans({
    variable: "--font-dm-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${dmSans.variable} antialiased`}
            >
                <Header />
                <main>
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
